# https://golangci-lint.run/usage/configuration/#config-file
run:
  allow-parallel-runners: true
  timeout: 5m
  go: "1.21"
  tests: true

linters:
  enable-all: false
  disable-all: true
  enable:
    - depguard
    - errorlint
    - errcheck
    - exportloopref
    - gochecknoglobals
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomodguard
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gocritic:
    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint run` to see all tags and checks.
    # Empty list by default. See https://github.com/go-critic/go-critic#usage -> section "Tags".
    enabled-tags:
      - diagnostic
      - opinionated
      - style
    disabled-checks:
      - paramTypeCombine
      - unnamedResult
      - whyNoLint
  gomodguard:
    blocked:
      modules:
        - github.com/pkg/errors:
            recommendations:
              - errors
              - fmt
  lll:
    line-length: 150
  depguard:
    rules:
      all:
        deny:
          - pkg: io/ioutil
            desc: "io/ioutil package has been deprecated"

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - text: "G306:"
      linters:
        - gosec
    - text: "G204:"
      linters:
        - gosec
    - text: "G112:"
      linters:
        - gosec
