---
# Source: app-of-apps/templates/apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-service-bar
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/chime/mani-diffy.git
    path: charts/service
    helm:
      version: v3
      parameters:
      - name: env
        value: test
      valueFiles:
        - ../../overrides/service/bar/base.yaml
        - ../../overrides/service/bar/test.yaml
  syncPolicy:
    automated: {}
---
# Source: app-of-apps/templates/apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-service-baz
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/chime/mani-diffy.git
    path: charts/service
    helm:
      version: v3
      parameters:
      - name: env
        value: test
      valueFiles:
        - ../../overrides/service/baz/base.yaml
        - ../../overrides/service/baz/test.yaml
  syncPolicy:
    automated: {}
---
# Source: app-of-apps/templates/apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-service-foo
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/chime/mani-diffy.git
    path: charts/service
    helm:
      version: v3
      parameters:
      - name: env
        value: test
      valueFiles:
        - ../../overrides/service/foo/base.yaml
        - ../../overrides/service/foo/test.yaml
  syncPolicy:
    automated: {}
