---
name: tests

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, ready_for_review]

jobs:
  go_test:
    # strategy:
    #   matrix:
    #     go-versions: [1.18.x]
    #     os: [ubuntu-latest, macos-latest]
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up go version
        uses: actions/setup-go@v3
        with:
          # go-version: ${{ matrix.go-versions }}
          go-version: '1.20'
      - name: run go tests
        run: |
          go test -v ./...
  golangci:
    # https://github.com/golangci/golangci-lint-action
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          # use config in .golangci.yaml to configure the action further
